TABLAS PARA EL SISTEMA HELP DESK

-Empleado
-Departamentos
-Tipo Incidencia(id, tipo)
-Casos
-Estado caso
-Repuestos 
-Historial Caso
-Productos Software
-Login
-Puesto de trabajo
-SLA(id, tiempo de resolución, tiempo de primera respuesta, tiempo max, tiempo minimo)
-Encuesta de satisfacción
-Solicitud de repuestos
-Notificaciones 
-Prioridad

-----------------------------------SCRIPTS---------------------------------------

-- 1. Departamentos
CREATE TABLE Departamentos (
    id_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255)
);

-- 2. Estado_Caso
CREATE TABLE Estado_Caso (
    id_estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

-- 3. Prioridad
CREATE TABLE Prioridad (
    id_prioridad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

-- 4. Tipo_Incidencia
CREATE TABLE Tipo_Incidencia (
    id_tipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(100) NOT NULL
);

-- 5. Empleado
CREATE TABLE Empleado (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE NOT NULL,
    telefono VARCHAR2(20),
    rol VARCHAR2(50) CHECK (rol IN ('USUARIO','AGENTE','SUPERVISOR','ADMIN')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    CONSTRAINT fk_empleado_departamento FOREIGN KEY (id_departamento) REFERENCES Departamentos(id_departamento)
);

-- 6. Casos
CREATE TABLE Casos (
    id_caso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado_solicita NUMBER NOT NULL,
    id_tipo_incidencia NUMBER NOT NULL,
    titulo VARCHAR2(200) NOT NULL,
    descripcion CLOB NOT NULL,
    id_prioridad NUMBER,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_caso_empleado FOREIGN KEY (id_empleado_solicita) REFERENCES Empleado(id_empleado),
    CONSTRAINT fk_caso_tipo FOREIGN KEY (id_tipo_incidencia) REFERENCES Tipo_Incidencia(id_tipo),
    CONSTRAINT fk_caso_prioridad FOREIGN KEY (id_prioridad) REFERENCES Prioridad(id_prioridad)
);

-- 7. Repuestos
CREATE TABLE Repuestos (
    id_repuesto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    stock NUMBER DEFAULT 0 CHECK (stock >= 0),
    precio_unitario NUMBER(10,2) CHECK (precio_unitario >= 0)
);

-- 8. Historial_Caso
CREATE TABLE Historial_Caso (
    id_historial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso NUMBER REFERENCES Casos(id_caso),
    fecha DATE DEFAULT SYSDATE,
    comentario CLOB,
    id_estado NUMBER REFERENCES Estado_Caso(id_estado),
    id_empleado NUMBER REFERENCES Empleado(id_empleado)
);

-- 9. Solicitud_Repuestos
CREATE TABLE Solicitud_Repuestos (
    id_caso NUMBER REFERENCES Casos(id_caso),
    id_repuesto NUMBER REFERENCES Repuestos(id_repuesto),
    cantidad NUMBER DEFAULT 1 CHECK (cantidad > 0),
    PRIMARY KEY (id_caso, id_repuesto)
);

-- 10. Encuesta_Satisfaccion
CREATE TABLE Encuesta_Satisfaccion (
    id_encuesta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso NUMBER REFERENCES Casos(id_caso),
    calificacion NUMBER CHECK (calificacion BETWEEN 1 AND 5),
    comentario VARCHAR2(500),
    fecha_respuesta TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 11. Notificaciones
CREATE TABLE Notificaciones (
    id_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso NUMBER REFERENCES Casos(id_caso),
    id_empleado NUMBER REFERENCES Empleado(id_empleado),
    mensaje VARCHAR2(255),
    estado VARCHAR2(50) CHECK (estado IN ('Encolado','Enviado','Visto'))
);

CREATE TABLE SLA (
    id_sla NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiempo_resolucion INTERVAL DAY TO SECOND NOT NULL,
    tiempo_primer_respuesta INTERVAL DAY TO SECOND NOT NULL,
    tiempo_maximo INTERVAL DAY TO SECOND NOT NULL,
    tiempo_minimo INTERVAL DAY TO SECOND NOT NULL
);

ALTER TABLE Casos
ADD id_sla NUMBER REFERENCES SLA(id_sla);





--------------------------------------INSERTS-----------------------------------

-- 1. Departamentos
INSERT INTO Departamentos (nombre, descripcion) VALUES ('Soporte Técnico', 'Departamento de soporte técnico');
INSERT INTO Departamentos (nombre, descripcion) VALUES ('Sistemas', 'Departamento de sistemas y TI');

-- 2. Estado_Caso
INSERT INTO Estado_Caso (nombre) VALUES ('Asignado');
INSERT INTO Estado_Caso (nombre) VALUES ('En Proceso');
INSERT INTO Estado_Caso (nombre) VALUES ('Cerrado');
INSERT INTO Estado_Caso (nombre) VALUES ('Rechazado');

-- 3. Prioridad
INSERT INTO Prioridad (nombre) VALUES ('Alta');
INSERT INTO Prioridad (nombre) VALUES ('Media');
INSERT INTO Prioridad (nombre) VALUES ('Baja');

-- 4. Tipo_Incidencia
INSERT INTO Tipo_Incidencia (tipo) VALUES ('Impresora no funciona');
INSERT INTO Tipo_Incidencia (tipo) VALUES ('Pantalla congelada');
INSERT INTO Tipo_Incidencia (tipo) VALUES ('Otro');

-- 5. Empleados
INSERT INTO Empleado (id_departamento, nombre, apellido, correo, telefono, rol, activo)
VALUES (1, 'Juan', 'Pérez', 'juan.perez@empresa.com', '555-1234', 'AGENTE', 'S');

INSERT INTO Empleado (id_departamento, nombre, apellido, correo, telefono, rol, activo)
VALUES (2, 'Ana', 'Gómez', 'ana.gomez@empresa.com', '555-5678', 'USUARIO', 'S');

-- 6. Casos
INSERT INTO Casos (id_empleado_solicita, id_tipo_incidencia, titulo, descripcion, id_prioridad)
VALUES (2, 1, 'Impresora bloqueada', 'La impresora del área de finanzas no imprime', 1);

INSERT INTO Casos (id_empleado_solicita, id_tipo_incidencia, titulo, descripcion, id_prioridad)
VALUES (2, 2, 'Pantalla congelada', 'La pantalla de mi PC se queda congelada frecuentemente', 2);

-- 7. Repuestos
INSERT INTO Repuestos (nombre, descripcion, stock, precio_unitario)
VALUES ('Toner HP', 'Toner para impresora HP', 10, 75.50);

INSERT INTO Repuestos (nombre, descripcion, stock, precio_unitario)
VALUES ('Cable HDMI', 'Cable HDMI 2 metros', 20, 15.00);

-- 8. Historial_Caso
INSERT INTO Historial_Caso (id_caso, comentario, id_estado, id_empleado)
VALUES (1, 'Caso recibido y asignado al técnico', 1, 1);

INSERT INTO Historial_Caso (id_caso, comentario, id_estado, id_empleado)
VALUES (2, 'Se revisa el equipo y se reinicia el sistema', 2, 1);

-- 9. Solicitud_Repuestos
INSERT INTO Solicitud_Repuestos (id_caso, id_repuesto, cantidad) VALUES (1, 1, 1);
INSERT INTO Solicitud_Repuestos (id_caso, id_repuesto, cantidad) VALUES (2, 2, 1);

-- 10. Encuesta_Satisfaccion
INSERT INTO Encuesta_Satisfaccion (id_caso, calificacion, comentario) VALUES (1, 5, 'Servicio rápido y eficiente');
INSERT INTO Encuesta_Satisfaccion (id_caso, calificacion, comentario) VALUES (2, 4, 'Solución efectiva, pero tardó un poco');

-- 11. Notificaciones
INSERT INTO Notificaciones (id_caso, id_empleado, mensaje, estado)
VALUES (1, 1, 'Se asignó técnico al caso', 'Enviado');

INSERT INTO Notificaciones (id_caso, id_empleado, mensaje, estado)
VALUES (2, 1, 'Caso en revisión por soporte', 'Encolado');


INSERT INTO SLA (tiempo_resolucion, tiempo_primer_respuesta, tiempo_maximo, tiempo_minimo)
VALUES (
    INTERVAL '04:00:00' HOUR TO SECOND,  -- 4 horas
    INTERVAL '01:00:00' HOUR TO SECOND,  -- 1 hora
    INTERVAL '08:00:00' HOUR TO SECOND,  -- 8 horas
    INTERVAL '02:00:00' HOUR TO SECOND   -- 2 horas
);

INSERT INTO SLA (tiempo_resolucion, tiempo_primer_respuesta, tiempo_maximo, tiempo_minimo)
VALUES (
    INTERVAL '08:00:00' HOUR TO SECOND,  -- 8 horas
    INTERVAL '02:00:00' HOUR TO SECOND,  -- 2 horas
    INTERVAL '12:00:00' HOUR TO SECOND,  -- 12 horas
    INTERVAL '04:00:00' HOUR TO SECOND   -- 4 horas
);




UPDATE Casos SET id_sla = 1 WHERE id_caso = 1;
UPDATE Casos SET id_sla = 2 WHERE id_caso = 2;




